# Generated by Django 2.2.18 on 2021-03-25 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210322_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 15, 57, 33, 942244, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
